### ISSUE TITLE
Review Code

### ISSUE THREAD

**Issue by Aleksandr112Kupruk222** [Kreytal/U_W#1]
The code is well documented , there plentifull amount of comments that easily allow to understand the code.
-The code is of a high quality, however I noticed that it can be slightly improved in terms of error handling, if you look at this line of code.
https://github.com/Kreytal/U_W/blob/fdbae2728bceba9ea9fc93cbb14c77728e67dec6/Testing.cs#L19
You can see that you used a boolen to call the shuffle method which is good as methods requires to return bool , howerver you didnt seem to use this boolen in any way expept simply calling the method, I propose that you implement a check if this boolean returns true then that means that shuffel was sucsefful, else it wasnt then you can output that to a user , it is unlikely scenario however its better to be safe.
https://github.com/Kreytal/U_W/blob/fdbae2728bceba9ea9fc93cbb14c77728e67dec6/Testing.cs#L19-L37
In overall the code is great, error handling with this addition will be improved.

**Comment by Kreytal** [comment]
Thanks for your review, I indeed forgot to use the boolean, thanks for pointing it out - Fixed.
